version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.19.1
  agent: percy/agent@0.1.3
jobs:
  Portfolio-Run:
    executor:
      name: node/default
      commands:
        parameters:
          percy_token:
            description: To run snapshot tests.
            type: string
            default: $PERCY_TOKEN
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run percy:run
workflows:
    Porffolio-Run:
      jobs:
        - Portfolio-Run