version: 2.1
jobs:
  Build-and-Run:
    docker:
      - image: cypress/browsers
    steps:
      - checkout
      - run: echo $PERCY_TOKEN
      - run: npm install
      - run: npm run percy:ci
      - store_artifacts:
        path: cypress/videos
      - store_artifacts:
        path: cypress/screenshots
workflows:
  version: 2.1
  Portfolio-Tests:
    jobs:
      - Build-and-Run