version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.16.1
  workflows:
    runningdocker:
      machine: true
      jobs:
   steps:
     - checkout
     # build the application image
     - run: npm run docker:build
     # running the image
     - run: npm run docker:run
    runningcypress:
      jobs:
     - cypress/run:
workflows:
  Portfolio-Tests:
      jobs:
        - runningdocker
        - runningcypress