version: 2.1
orbs:
  docker: circleci/docker@1.0.1
  cypress: cypress-io/cypress@1.16.1
  workflows:
    check-and-build-only:
      executor: docker/machine
      steps:
        - checkout
        - docker/check
        - docker/build:
            image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            runcypress:
              jobs:
                - cypress/run:
workflows:
  Portfolio-Tests:
      jobs:
        - check-and-build-only
        - cypress/run