version: 2.1
jobs:
  Portfolio-Run:
    build:
      docker:
        - image: davedevil/online-portfolio:latest
        cypress:
          - image: cypress-io/cypress@1.19.1
          percy:
            - image: percy/agent@0.1.2
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run cypress:run
workflows:
    Porffolio-Run:
      jobs:
        - Portfolio-Run