version: 2.1
jobs:
    runningdocker:
      docker:
        - image: circleci/node
      machine: true
   steps:
     - checkout
     # build the application image
     - run: npm run docker:build
     # running the image
     - run: npm run docker:run
    runningcypress:
      docker:
        - image: cypress/browsers
        steps:
        - checkout
        - run: npm run cypress:run
workflows:
  version: 2.1
  Portfolio-Tests:
      jobs:
        - runningdocker
        - runningcypress