version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.16.1
jobs:
  Portfolio-Tests:
  steps:
    - run: 'npm start & wait-on http://localhost:8080'
    - cypress/run:
      executor: cypress/browsers-chrome73-ff68
      browser: chrome
workflows:
  Portfolio-Tests:
    jobs:
      - Portfolio-Tests
      - cypress/run
