version: 2.1
jobs:
  buildandrun:
    docker:
      - image: cypress/browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run docker:build
      - run: npm run docker:run
      - run: npm run cypress:run
workflows:
  version: 2.1
  Portfolio-Tests:
    jobs:
      - buildandrun