version: 2.1
jobs:
  Portfolio-Run:
    docker:
      - image: circleci/node:latest-browsers
    parallelism: 4
    steps:
      - checkout
      - command: jest --collectCoverage=true
      - run: echo $PERCY_TOKEN
      - run: echo $CYPRESS_RECORD_KEY
      - run: npm install
      - run: npm run percy:ci
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
workflows:
  version: 2.1
  Portfolio-CI:
    jobs:
      - Portfolio-Run