version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.0
  cypress: cypress-io/cypress@1.16.1
  percy: percy/agent@0.1.2
commands:
    Add_Percy_Token:
      description: Finalize all Percy builds
      parameters:
        percy_token:
          description: Adding PERCY_TOKEN to the build.
          type: string
          default: $PERCY_TOKEN
      steps:
        - run: PERCY_TOKEN=<< parameters.percy_token >> percy finalize --all
jobs:
  Portfolio-Run:
    steps:
      - checkout
      - run: npm install
      - run: npm start & wait-on http://localhost:8080
      - run: npm run percy:run
workflows:
  Add_Percy_Token:
  Portfolio-Run:
      jobs:
        - Add_Percy_Token
        - Portfolio-Run