version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.16.1
  percy: percy/agent@0.1.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: export PERCY_TOKEN=9ab2ef6b86ac947038d82c2673f4924771bc3751ba2bdb572ed2bbe9ecd7c69f
            - run: npm run start & wait-on http://localhost:8080
            - run: npm run percy:run
workflows:
    build-and-test:
      jobs:
        - build-and-test