version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: davedevil/online-portfolio:0.0.1
  Portfolio-Run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
              name: "Percy"
              command: |
                echo $PERCY_TOKEN
            - run: npm install
            - run: npm run docker:run
            - run: npm run percy:run
workflows:
    Porffolio-Run:
      jobs:
        - Portfolio-Run