version: 2.1
jobs:
  Build-and-Run:
    docker:
      - image: cypress/browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run ci:run
workflows:
  version: 2.1
  Portfolio-Tests:
    jobs:
      - Build-and-Run