version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.16.1
  workflows:
    build:
      jobs:
        - cypress/install:
          build: npm run build
        - cypress/run:
          requires:
            - cypress/install
workflows:
  Portfolio-Tests:
      jobs:
        - cypress/install
        - cypress/run