version: 2.1
jobs:
  Build-and-Run:
    docker:
      - image: cypress/browsers
    steps:
      - checkout
      - run: 
        name: "echo an env var that is part of our project"
        command: |
          echo $PERCY_TOKEN # this env var must be swt within the project
      - run: npm install
      - run: npm run percy:ci
workflows:
  version: 2.1
  Portfolio-Tests:
    jobs:
      - Build-and-Run