version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: davedevil/online-portfolio:latest
  Portfolio-Run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: docker pull davedevil/online-portfolio:latest
            - run: export PERCY_TOKEN=9ab2ef6b86ac947038d82c2673f4924771bc3751ba2bdb572ed2bbe9ecd7c69f
            - run: npm run percy:run
workflows:
    Porffolio-Run:
      jobs:
        - Portfolio-Run