version: 2.1
orbs:
  node: davedevil/online-portfolio:latest
  cypress: cypress-io/cypress@1.19.1
  percy: percy/agent@0.1.2
jobs:
  Portfolio-Run:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run cypress:run
workflows:
    Porffolio-Run:
      jobs:
        - Portfolio-Run